select id,name,phone,email,active,"createdAt","updatedAt","encryptedPassword","confirmationToken","confirmedAt","sex",birthday,"MerchantId","resetPasswordToken",occupation,
case when "city" like '%jaka%' or "city" like '%Jaka%' then 'DKI Jakarta' 
when "city" like '%bandu%' or "city" like '%Bandu%' then 'Bandung'
when "city" like '%tange%' or "city" like '%Tange%' then 'Tangerang'
when "city" like '%surab%' then 'Surabaya'
when "city" like '%semar%' then 'Semarang'
when "city" like '%cileg%' then 'Cilegon'
when "city" like '%sera%' then 'Serang'
when "city" like '%tange%' then 'Tangerang'
when "city" like '%beka%' or "city" like '%Beka%' then 'Bekasi'
when "city" like '%bog%' or "city" like '%Bog%' then 'Bogor'
when "city" like '%cima%' then 'Cimahi'
when "city" like '%cireb%' then 'Cirebon'
when "city" like '%depo%' or "city" like '%Depo%' then 'Depok'
when "city" like '%sukab%' then 'Sukbumi'
when "city" like '%tasik%' then 'Tasikmalaya'
when "city" like '%purwo%' then 'Purwokerto'
when "city" like '%sala%' then 'Salatiga'
when "city" like '%surak%' or "city" like '%Surak%' then 'Surakarta'
when "city" like '%bat%' or "city" like '%Bat%' then 'Batu'
when "city" like '%kedi%' then 'Kediri'
when "city" like '%madi%' then 'Madiun'
when "city" like '%mala%' then 'Malang'
when "city" like '%pasu%' then 'Pasuruan'
when "city" like '%yogy%' or "city" like '%jogj%' or "city" like '%Jogj%' then 'Yogyakarta'
else 'Unknown' end "city",address
from "STG_Customers"